# Base Docker Compose Configuration
# Use docker-compose.dev.yml for development
# Use docker-compose.prod.yml for production
#
# Usage:
#   Development: docker-compose -f docker-compose.dev.yml up
#   Production:  docker-compose -f docker-compose.prod.yml up
#
# This file is kept for reference and can be removed if not needed.

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: expendi-analytics-db
    environment:
      POSTGRES_DB: expendi_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  analytics-backend:
    build: .
    container_name: expendi-analytics-backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/expendi_analytics
      - PORT=3001
      - NODE_ENV=development
      - SUBGRAPH_URL_BASE_MAINNET=${SUBGRAPH_URL_BASE_MAINNET:-https://api.studio.thegraph.com/query/118246/expendi-base/v1.0.0}
      - SUBGRAPH_URL_BASE_SEPOLIA=${SUBGRAPH_URL_BASE_SEPOLIA:-}
      - SUBGRAPH_URL_CELO_MAINNET=${SUBGRAPH_URL_CELO_MAINNET:-}
      - SUBGRAPH_URL_CELO_ALFAJORES=${SUBGRAPH_URL_CELO_ALFAJORES:-}
      - SUBGRAPH_URL_SCROLL_MAINNET=${SUBGRAPH_URL_SCROLL_MAINNET:-}
      - SUBGRAPH_URL_SCROLL_SEPOLIA=${SUBGRAPH_URL_SCROLL_SEPOLIA:-}
      - DEFAULT_CHAIN=${DEFAULT_CHAIN:-base}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-0 */5 * * * *}
      - ANALYTICS_INTERVAL=${ANALYTICS_INTERVAL:-0 0 * * *}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: expendi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data: